---
- name: Install Packages
  apt:
    name:
      - git
    update_cache: yes
    state: latest
  become: yes

- name: Checkout RedELK git repo
  git:
    repo: 'https://github.com/outflanknl/RedELK.git'
    dest: "/tmp/redelk_latest"
  ignore_errors: yes

- name: Updating certs/config.conf
  lineinfile:
   dest: /tmp/redelk_latest/certs/config.cnf
   regexp: "{{ item.regexp }}"
   line: "{{ item.line }}"
  with_items:
    - {regexp: '^C = ', line: 'C = {{ cert_C }}'}
    - {regexp: '^ST = ', line: 'ST = {{ cert_ST }}'}
    - {regexp: '^L = ', line: 'L = {{ cert_L }}'}
    - {regexp: '^O = ', line: 'O = {{ cert_O }}'}
    - {regexp: '^OU = ', line: 'OU = {{ cert_OU }}'}
    - {regexp: '^CN = ', line: 'CN = {{ cert_CN }}'}
    - {regexp: '^emailAddress = ', line: 'emailAddress = {{ cert_email }}'}
    - {regexp: '^DNS.1 = ', line: 'DNS.1 = {{ redelk_server_host }}'}
    - {regexp: '^DNS.2 = ', line: ""}
    - {regexp: '^IP.1 = ', line: ""}
  tags: [prep_cert]

- name: Updating alarm.json.conf
  lineinfile:
    dest: /tmp/redelk_latest/elkserver/mounts/redelk-config/etc/redelk/config.json
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {regexp: '^ "enable_letsencrypt', line: ' "enable_letsencrypt":"{{ enable_letsencrypt }}",'}
    - {regexp: '^ "external_domain', line: ' "external_domain":"{{ redelk_server_host }}",'}
    - {regexp: '^ "le_email', line: ' "le_email":"{{ le_email }}",'}
    - {regexp: '^ "interval', line: ' "interval":"{{ alarm_interval }}",'}
    - {regexp: '^ "vt_apikey', line: ' "vt_apikey":"{{ alarm_vtapikey }}",'}
    - {regexp: '^ "HybridAnalysis', line: ' "HybridAnalysisAPIKEY":"{{ alarm_haapikey }}",'}
    - {regexp: '^ "smtpSrv', line: ' "smtpSrv":"{{ alarm_smtpsrv }}",'}
    - {regexp: '^ "smtpPort', line: ' "smtpPort":"{{ alarm_smtpport }}",'}
    - {regexp: '^ "smtpName', line: ' "smtpName":"{{ alarm_smtpname }}",'}
    - {regexp: '^ "smtpPass', line: ' "smtpPass":"{{ alarm_smtppass }}",'}
    - {regexp: '^ "fromAddr', line: ' "fromAddr":"{{ alarm_fromaddr }}",'}
    - {regexp: '^ "toAddrs', line: ' "toAddrs":["{{ alarm_toaddr }}"],'}
    - {regexp: '^ "tempDir', line: ' "tempDir":["{{ alarm_tempdir }}"],'}
  tags: [prep_alarm]

- name: Updating RedElk cobaltstrike path
  replace:
    path: "{{ item.dest }}"
    regexp: '\/root\/cobaltstrike'
    replace: "{{ cobaltstrike_install_dir }}"
  with_items:
    - {dest: /tmp/redelk_latest/c2servers/filebeat/filebeat_cobaltstrike.yml}
    - {dest: /tmp/redelk_latest/c2servers/scripts/copydownloads_cobaltstrike.sh}
    - {dest: /tmp/redelk_latest/c2servers/scripts/export_cobaltstrikedata.sh}
    - {dest: /tmp/redelk_latest/c2servers/cron.d/redelk_cobaltstrike}
  tags: [prep_cobaltstrike]

- name: Executing RedElk init script.
  command:
    chdir: /tmp/redelk_latest
    cmd: ./initial-setup.sh ./certs/config.cnf
  register: exec_output
  ignore_errors: true
  tags: [prep_init]

- name: Checking for failures
  fail:
    msg: "Error occurred. Check /tmp/redelk_latest/redelk-initialsetup.log for details."
  when: '"ERROR" in exec_output.stdout'
  tags: [prep_init]
